text = "THIS IS A WIP DECOMP,\nA BUNCH OF STUFF WILL BE MISSING\nNOR IS IT FULLY COMPLETE\nBUT IT SHOULD BE GOOD FOR MODDING USE\nGOOD LUCK AND HAVE FUN MODDING!"
xorigin = 1
yorigin = 0
font = global.smallfont
